"""remove test column_again

Revision ID: f6383f14a121
Revises: ad116cc53429
Create Date: 2026-02-03 05:10:42.007806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f6383f14a121"
down_revision: Union[str, Sequence[str], None] = "ad116cc53429"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "test_column")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("test_column", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
